[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.1",
    "joblib>=1.5.1",
    "lightgbm>=4.6.0",
    "pymupdf>=1.26.3",
    "scikit-learn>=1.7.0",
    "werkzeug>=3.1.3",
]
